services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      # - /app/node_modules  # Commenté temporairement
    environment:
      NODE_ENV: development
      # JWT_SECRET: Bopessss
    env_file:
      - ./.env.dev
    depends_on:
      - mongodb
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: newproject
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local